- name: Looping list
  hosts: localhost
  gather_facts: false
  vars:
    filename: "list_user_dev_managed2.yml"
    output_content: []
  tasks:
    - name: Generate list
      set_fact:
        output_content: "{{ output_content + ['- dev' + item | string] }}"
      loop: "{{ range(51, 101) | list }}"

    - name: Create output file
      template:
        src: ./template.j2
        dest: "{{ filename }}"
      vars:
        output_content: "{{ output_content }}"
